### ISSUE TITLE
Missing plugin files

### ISSUE THREAD

**Issue by 3v1lman** [Qvin0000/ExileApiPlugins#15]
Some plugins need specific files to work that are not currently included, for example:

- PassiveSkillTreePlanter - SkillTreeData.dat
(old version can be found here https://github.com/Stridemann/PoE_PassiveSkillTreePlanter)

- MapsExchange - ImagesAtlas.png
(gives an error when trying to activate the plugin: Plugins\Compiled\MapsExchange\images\ImagesAtlas.png not found.)

**Comment by skydrome** [comment]
Here is the 3.8 tree if you didnt already find out how to make it yourself
https://gist.github.com/skydrome/ecb0eb970d94138545128adedd58a499

**Comment by NoNick96** [comment]
I have the same issue with MapsExchange

**Comment by NoNick96** [comment]
I've created a dummy file called "ImagesAtlas.png" and placed it in the plugin's directory. Some of the features are partially working. It means It's showing three of the same map and exp penalty in stash, but nothing else. The plugin also generates a lot of errors.

This one shows once, when the plugin is turned on:
`2019-09-24 14:04:05.570 +02:00 [Error] MapsExchange, Initialise -> SharpDX.SharpDXException: HRESULT: [0x88982F50], Module: [SharpDX.WIC], ApiCode: [WINCODEC_ERR_COMPONENTNOTFOUND/Componentnotfound], Message: The component cannot be found.
   at SharpDX.Result.CheckError() in C:\projects\sharpdx\Source\SharpDX\Result.cs:line 195
   at SharpDX.WIC.ImagingFactory.CreateDecoderFromFilename(String filename, Nullable1 guidVendorRef, Int32 desiredAccess, DecodeOptions metadataOptions, BitmapDecoder decoderOut) in C:\projects\sharpdx\Source\SharpDX.Direct2D1\Generated\DESKTOP_APP\WIC\Interfaces.cs:line 3942
   at SharpDX.WIC.BitmapDecoder..ctor(ImagingFactory factory, String filename, DecodeOptions metadataOptions) in C:\projects\sharpdx\Source\SharpDX.Direct2D1\WIC\BitmapDecoder.cs:line 129
   at ExileCore.RenderQ.TextureLoader.LoadBitmap(ImagingFactory2 factory, String filename) in D:\NoNick\afdsgs\ExileApi\Core\RenderQ\TextureLoader.cs:line 23
   at ExileCore.RenderQ.SpritesRender.LoadPng(String fileName) in D:\NoNick\afdsgs\ExileApi\Core\RenderQ\SpritesRender.cs:line 188
   at ExileCore.Graphics.InitImage(String name, Boolean textures) in D:\NoNick\afdsgs\ExileApi\Core\Graphics.cs:line 195
   at MapsExchange.MapsExchange.Initialise() in D:\NoNick\afdsgs\PoeHelper\Plugins\Source\MapsExchange\MapsExchange.cs:line 193
   at ExileCore.Shared.PluginWrapper.pluginInitialise() in D:\NoNick\afdsgs\ExileApi\Core\Shared\PluginWrapper.cs:line 131
   at ExileCore.Shared.PluginWrapper.<>c__DisplayClass41_0.<Initialise>b__0(Object obj, Boolean value) in D:\NoNick\afdsgs\ExileApi\Core\Shared\PluginWrapper.cs:line 95
`

This one is generating when stash is opened:

`2019-09-24 14:10:03.432 +02:00 [Error] System.IO.FileNotFoundException: Texture by name: ImagesAtlas.png not found
   at ExileCore.RenderQ.DX11.GetTexture(String name) in D:\NoNick\afdsgs\ExileApi\Core\RenderQ\DX11.cs:line 243
   at ExileCore.RenderQ.SpritesRender.DrawImage(String fileName, RectangleF rect, RectangleF uv, Color color) in D:\NoNick\afdsgs\ExileApi\Core\RenderQ\SpritesRender.cs:line 305
`
This one is generating when the atlas is opened:

`2019-09-24 14:12:49.472 +02:00 [Error] Key 'LControlKey' is not registered. Use Input.RegisterKey(Settings.MyKey) in Initialize function for registration.`

`2019-09-24 14:13:00.453 +02:00 [Error] MapsExchange, Render -> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary2.get_Item(TKey key)
   at ExileCore.Input.IsKeyDown(Keys nVirtKey) in D:\NoNick\afdsgs\ExileApi\Core\Input.cs:line 62
   at MapsExchange.MapsExchange.DrawAtlasMaps() in D:\NoNick\afdsgs\PoeHelper\Plugins\Source\MapsExchange\MapsExchange.cs:line 321
   at MapsExchange.MapsExchange.Render() in D:\NoNick\afdsgs\PoeHelper\Plugins\Source\MapsExchange\MapsExchange.cs:line 207
   at ExileCore.Shared.PluginWrapper.Render() in D:\NoNick\afdsgs\ExileApi\Core\Shared\PluginWrapper.cs:line 220
`

**Comment by NoNick96** [comment]
So I made MapsExchange fully work by creating a dummy ImagesAtlas.png file, which is just a red square 70x70 pixels and placing it inside PoeHelper\Plugins\Compiled\MapsExchange\images. 
The rest of the required .png files can be downloaded [here](https://github.com/zaafar/poehud_mapsexchange).
